spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/roamnest_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=sndlksksklklsdlfksdlk93932lksmdklsmdlasadmlasmksadmalks9as9sa
jwt.expiration-ms=86400000